name: Deploy

on:
  push:
    tags:
      - v*
      
env:
  BASE_IMAGE_NAME: ghcr.io/${{ github.repository }}
  PRERELEASE_IMAGE_NAME: "${{ env.BASE_IMAGE_NAME }}-prerelase:${{ github.sha }}"
      
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Pull pre-release
        run: docker pull ${{ env.PRERELEASE_IMAGE_NAME }}
      
      - name: Retag pre-release
        id: retag
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          
          echo IMAGE_ID=${{ env.BASE_IMAGE_NAME }}
          echo VERSION=$VERSION
          
          docker tag "${{ env.PRERELEASE_IMAGE_NAME }}" ${{ env.BASE_IMAGE_NAME }}:$VERSION
          echo "::set-output name=RELEASE_IMAGE::${{ env.BASE_IMAGE_NAME }}:${VERSION}"
        
      - name: Push release
        run: docker push ${{ steps.retag.outputs.RELEASE_IMAGE }}
        
        
        
      
