name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Verison to release (major, minor, patch)'
        required: true

jobs:
  release:
    name: Release creation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
      
      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Get next versions available
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Resolve release version
        id: nextvers
        run: |
          if [ "${{ github.event.inputs.version }}" = "major" ]; then 
            echo "::set-output name=RELEASE_VERSION::${{ steps.semvers.outputs.v_major }}"
          elif [ "${{ github.event.inputs.version }}" = "minor" ]; then
            echo "::set-output name=RELEASE_VERSION::${{ steps.semvers.outputs.v_minor }}"
          elif [ "${{ github.event.inputs.version }}" = "patch" ]; then
            echo "::set-output name=RELEASE_VERSION::${{ steps.semvers.outputs.v_patch }}"
          else
            echo "Please specify either 'major', 'minor', 'patch' version"
            exit 1
          fi

      - uses: actions/create-release@v1
        name: Create release
        with:
          tag_name: ${{ steps.nextvers.outputs.RELEASE_VERSION }}
          release_name: Release ${{ steps.nextvers.outputs.RELEASE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
