name: CI

on:
  push:
    branches: [ master ]
    
env: 
  IMAGE_ID: ghcr.io/${{ github.repository }}-rc:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Docker build
        uses: docker/build-push-action@v2.3.0
        with:
          tags: ${{ env.IMAGE_ID }}
