name: On New Tag

on:
  push:
    tags:
      - v*

env:
  BASE_IMAGE_NAME: ghcr.io/${{ github.repository }}
  PRERELEASE_IMAGE_NAME: ghcr.io/${{ github.repository }}-rc:${{ github.sha }}
  SERVICE_NAME: api

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Pull pre-release
        run: docker pull ${{ env.PRERELEASE_IMAGE_NAME }}
      
      - name: Find New Version
        id: version
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          
          echo VERSION=$VERSION
          echo "::set-output name=RELEASE_VERSION::${VERSION}"
        
      - name: Push release
        run: |
          docker tag "${{ env.PRERELEASE_IMAGE_NAME }}" ${{ env.BASE_IMAGE_NAME }}:${{ steps.version.outputs.RELEASE_VERSION }}
          docker push ${{ env.BASE_IMAGE_NAME }}:${{ steps.version.outputs.RELEASE_VERSION }}
        
      - name: Deploy with SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          script: |
            cd /opt/hooka
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            sed -i "s/tatosea\/hookah-mixes-server:.*/tatosea\/hookah-mixes-server:${{ steps.version.outputs.RELEASE_VERSION }}/g" docker-compose.yml
            docker-compose pull ${{ env.SERVICE_NAME }}
            docker-compose up -d ${{ env.SERVICE_NAME }}
            docker logout ghcr.io