# This is a basic workflow to help you get started with Actions

name: Release Workflow

on:
  push:
    branches: [ master ]
  pull_request: 

jobs:
  release-drafter:
    name: Release Drafter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build image
        id: build
        uses: docker/build-push-action@v2.3.0
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}-prerelease:${{ github.sha }}
      
      - name: Comment PR with Docker Image
        uses: actions/github-script@0.3.0
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            github.issues.createComment({ issue_number, owner, repo, body: "Bulded Docker image: ${{ steps.build.outputs.digest }}" });
      
      - name: Release Drafter
        if: ${{ github.event_name == 'push' }}
        uses: release-drafter/release-drafter@v5.15.0
        with:
          publish: true
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
