# This is a basic workflow to help you get started with Actions

name: Test & Build

on:
  push:
    branches: [ master ]
  pull_request: 
  
env: 
  IMAGE_ID: ghcr.io/${{ github.repository }}-prerelease:${{ github.sha }}

jobs:
  build-push:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to GitHub Container Registry
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build image
        id: build
        uses: docker/build-push-action@v2.3.0
        with:
          tags: ${{ env.IMAGE_ID }}
          
      - name: Test compile
        run: docker run -it --entrypoint="" ${{ env.IMAGE_ID }} python -m py_compile ./main.py
      
      - name: Release Drafter
        if: ${{ github.event_name == 'push' }}
        uses: release-drafter/release-drafter@v5.15.0
        with:
          publish: true
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
