# This is a basic workflow to help you get started with Actions

name: Release Drafter

on:
  push:
    branches: [ master ]

jobs:
  release-drafter:
    name: Release Drafter
    runs-on: ubuntu-latest
    steps:  
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5.15.0
        with:
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
